version: '2.1'

services:

#Governing microservices
  customer-details:
   build: /
   depends_on:
    postgres:
     condition: service_healthy
   restart: always
   network_mode: "host"

   hostname: localhost
   ports:
    - 8091:8091
   healthcheck:
    test: "exit 0"



#MYSQL DATABASE
  postgres:
   image: postgres
   ports:
      - 5432:5432
   container_name: postgres
   mem_limit: 500m
   environment: 
    - POSTGRES_DB=testdb
   network_mode: "host"
   hostname: localhost
   restart: always
   healthcheck:
    test: "exit 0"
#CHECKING
  grafana:
   image: grafana/grafana
   container_name: grafana
   network_mode: "host"
   hostname: localhost
   ports:
    - 9086:9086
   environment:
    - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
    - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
    - GF_USERS_ALLOW_SIGN_UP=false
   restart: always
   healthcheck:
    test: "exit 0"






