global: 
  scrape_interval:     20s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['172.31.12.234:9090']
      
  - job_name: 'customer-details'
    static_configs:
      - targets: ['172.31.12.234:8091']